In [2]:
import pandas as pd

### 1. 공공데이터 포털 파일데이터 불러오기

In [1]:
houseDataUrl = "https://www.data.go.kr/cmm/cmm/fileDownload.do?atchFileId=FILE_000000002554243&fileDetailSn=1&dataNm=%ED%95%9C%EA%B5%AD%EC%A3%BC%ED%83%9D%EA%B8%88%EC%9C%B5%EA%B3%B5%EC%82%AC_%EC%A7%80%EC%97%AD%EB%B3%84%20PIR%20%EB%B0%8F%20LIR_20211231"

In [5]:
try:
    houseDataDf = pd.read_csv(houseDataUrl)
except Exception as e:
    print(e)
    houseDataDf = pd.read_csv(houseDataUrl, encoding="ms949")

'utf-8' codec can't decode byte 0xbf in position 0: invalid start byte

In [8]:
houseDataDf.tail(10)

,연도,월,전국소득대비 주택가격 비율,서울소득대비 주택가격 비율,부산소득대비 주택가격 비율,대구소득대비 주택가격 비율,인천소득대비 주택가격 비율,광주소득대비 주택가격 비율,대전소득대비 주택가격 비율,울산소득대비 주택가격 비율,...,세종 평균 연소득 대비 평균 대출금액,경기 평균 연소득 대비 평균 대출금액,강원 평균 연소득 대비 평균 대출금액,충북 평균 연소득 대비 평균 대출금액,충남 평균 연소득 대비 평균 대출금액,전북 평균 연소득 대비 평균 대출금액,전남평균 연소득 대비 평균 대출금액,경북 평균 연소득 대비 평균 대출금액,경남 평균 연소득 대비 평균 대출금액,제주 평균 연소득 대비 평균 대출금액
203,2021,2,6.84,9.03,6.77,6.77,7.30,6.54,7.11,5.82,...,5.03,4.08,2.84,2.93,2.91,2.81,2.86,2.93,3.13,3.27
204,2021,3,6.96,9.25,6.42,6.92,7.32,6.41,6.92,6.14,...,5.06,4.12,2.88,2.89,2.95,2.78,2.83,2.95,3.12,3.50
205,2021,4,7.01,9.09,6.77,7.30,7.58,6.57,7.15,5.78,...,4.28,4.13,3.02,2.91,3.00,2.68,2.83,3.48,3.06,3.46
206,2021,5,7.05,8.98,7.03,7.22,7.70,6.50,7.03,6.09,...,5.31,4.26,2.92,2.82,2.93,2.65,2.86,3.20,2.97,4.01
207,2021,6,6.79,8.79,6.83,6.69,7.29,6.60,7.06,5.69,...,4.96,4.22,2.74,2.97,2.96,3.03,2.99,3.18,3.01,3.40
208,2021,7,6.98,9.11,7.68,6.82,7.65,6.44,7.25,5.52,...,3.91,4.31,2.91,2.78,3.27,2.68,3.29,2.96,3.04,3.67
209,2021,8,6.74,8.41,7.32,7.08,7.37,6.73,7.73,5.99,...,5.03,4.25,3.11,2.90,3.06,2.94,2.98,3.10,3.23,4.12
210,2021,9,6.70,8.76,7.75,6.99,7.83,6.56,7.14,6.08,...,4.11,4.27,2.79,2.72,3.15,2.96,3.52,2.88,3.06,3.86
211,2021,10,6.69,8.55,6.91,7.67,8.92,7.17,6.72,6.65,...,4.85,4.53,2.98,2.58,2.99,2.71,3.11,2.87,2.98,4.59
212,2021,11,7.10,0.00,10.75,15.29,12.03,7.47,7.11,7.42,...,0.00,4.36,2.28,1.71,3.89,1.89,2.69,3.47,3.65,6.62

### [실습] 우편번호 검색 후 데이터 불러오기

In [9]:
postCodeUrl = "https://www.data.go.kr/cmm/cmm/fileDownload.do?atchFileId=FILE_000000002336443&fileDetailSn=1&dataNm=%ED%86%B5%EA%B3%84%EC%B2%AD_%EB%82%98%EB%9D%BC%ED%86%B5%EA%B3%84_%EC%9A%B0%ED%8E%B8%EB%B2%88%ED%98%B8_20211110"

In [12]:
postCodeDf = pd.read_csv(postCodeUrl, encoding="ms949")
postCodeDf

### 2. 국가통계포털(kosis) 데이터 수집

In [13]:
koreaPersonCntUrl = "https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MjUzMTdiMjcyZjQwY2VkMWJkY2RkYTRmZDkwMWQ3ZGY=&itmId=T20+T21+T22+&objL1=00+11+26+27+28+29+30+31+36+41+51+43+44+52+46+47+48+50+&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=M&newEstPrdCnt=12&orgId=101&tblId=DT_1B040A3"

In [20]:
pd.DataFrame( [ {"TBL_NM":"남성", "TBL_VALUE":"여성"},
                {"TBL_NM":"사과", "TBL_VALUE":"배"} ] )

  TBL_NM TBL_VALUE
0     남성        여성
1     사과         배

### 성별 인구수 데이터 수집

In [24]:
try:
    koreadPersonCntDf = pd.read_json(koreaPersonCntUrl)
except Exception as e:
    print(e)
    koreadPersonCntDf = pd.read_json(koreaPersonCntUrl, encoding="ms949")

In [28]:
koreadPersonCntDf.shape
koreadPersonCntDf

,TBL_NM,PRD_DE,TBL_ID,ITM_NM,ITM_NM_ENG,ITM_ID,UNIT_NM,ORG_ID,UNIT_NM_ENG,C1_OBJ_NM,C1_OBJ_NM_ENG,DT,PRD_SE,C1,C1_NM,C1_NM_ENG,LST_CHN_DE
0,행정구역(시군구)별 성별 인구수,202308,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,51377213,M,0,전국,Whole country,2023-09-04
1,행정구역(시군구)별 성별 인구수,202309,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,51370001,M,0,전국,Whole country,2023-10-05
2,행정구역(시군구)별 성별 인구수,202310,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,51354226,M,0,전국,Whole country,2023-11-03
3,행정구역(시군구)별 성별 인구수,202311,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,51337076,M,0,전국,Whole country,2023-12-11
4,행정구역(시군구)별 성별 인구수,202312,DT_1B040A3,총인구수,Koreans (Total),T20,명,101,Person,행정구역(시군구)별,By Administrative District,51325329,M,0,전국,Whole country,2024-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
643,행정구역(시군구)별 성별 인구수,202403,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,878519,M,52,전북특별자치도,Jeollabuk-do,2024-04-01
644,행정구역(시군구)별 성별 인구수,202404,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,877914,M,52,전북특별자치도,Jeollabuk-do,2024-05-07
645,행정구역(시군구)별 성별 인구수,202405,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,877281,M,52,전북특별자치도,Jeollabuk-do,2024-06-03
646,행정구역(시군구)별 성별 인구수,202406,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,876688,M,52,전북특별자치도,Jeollabuk-do,2024-07-04
647,행정구역(시군구)별 성별 인구수,202407,DT_1B040A3,여자인구수,Koreans (Female),T22,명,101,Person,행정구역(시군구)별,By Administrative District,875943,M,52,전북특별자치도,Jeollabuk-do,2024-08-01

### [실습] 소비자물가지수 수집

In [ ]:
xmlUrl = "https://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev?serviceKey=https://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev?serviceKey=서비스키&LAWD_CD=11110&DEAL_YMD=202407&pageNo=1&numOfRows=10&LAWD_CD=11110&DEAL_YMD=202407&pageNo=1&numOfRows=10"

In [30]:
priceRatioUrl = "https://kosis.kr/openapi/Param/statisticsParameterData.do?method=getList&apiKey=MjUzMTdiMjcyZjQwY2VkMWJkY2RkYTRmZDkwMWQ3ZGY=&itmId=T+&objL1=ALL&objL2=&objL3=&objL4=&objL5=&objL6=&objL7=&objL8=&format=json&jsonVD=Y&prdSe=M&newEstPrdCnt=3&orgId=101&tblId=INH_1J22003"
try:
    priceRatioDf = pd.read_json(priceRatioUrl)
except Exception as e:
    print(e)
    priceRatioDf = pd.read_json(priceRatioUrl, encoding="ms949")
priceRatioDf

### 3. 공공데이터포탈 XML 데이터 수집

In [53]:
# # 수집전략
# rowList = []
# columnList = []
# # 1개 행의 데이터를 하나씩 순차적으로 columnList에 저장
# columnList.append( 82500 )
# columnList.append( 2021 )
# # 1개 행 저장 완료 시 rowList 에 저장
# rowList.append( columnList )
# columnList = []
# # 1개 행의 데이터를 하나씩 순차적으로 columnList에 저장
# columnList.append( 52500 )
# columnList.append( 2020 )
# # 1개 행 저장 완료 시 rowList 에 저장
# rowList.append( columnList )
# columnList = []
# pd.DataFrame( rowList )

In [55]:
import requests
from lxml import html
import bs4
# for dealYearMonth .. 반복
# for eachLawCode in range(lawCodeList): 반복:
aptTradeDataUrl = f"http://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev?serviceKey=AT33s775KYpJOkUBJu0dxkJuUeIfDIOJRzAH084EQS3JN%2BzFjErLHuk%2FGZa9L4gBTSGCzeA69tI9PwLp7B37IQ%3D%3D&LAWD_CD=11110&DEAL_YMD=202407&pageNo=1&numOfRows=10"
resp = requests.get(aptTradeDataUrl)
xmlObj = bs4.BeautifulSoup( resp.text, "lxml-xml")

rowList = []
columnList = []
columnNameList = []

itemTag = xmlObj.find(name="items")
itemList = itemTag.findAll(name="item")
for j in range(0, len(itemList)):
    #itemList 한개를 가지고 rowList 만들어보자!
    eachRow = itemList[j]
    allColumns = eachRow.findAll()
    # 전체컬럼 데이터를 columnList에 저장한다
    for i in range(0, len(allColumns)):
        eachColumnValue = allColumns[i].text
        columnList.append(eachColumnValue)
        # 첫번째 행을 돌때만 column정보를 수집해서 저장
        if j == 0:
            columnNameList.append( allColumns[i].name )
    rowList.append( columnList)
    columnList = []
aptTradeDf = pd.DataFrame( rowList, columns = columnNameList  )
aptTradeDf

In [110]:
aptTradeDf = pd.DataFrame( rowList, columns = columnNameList  )

In [113]:
aptTradeDf

,aptDong,aptNm,aptSeq,bonbun,bubun,buildYear,buyerGbn,cdealDay,cdealType,dealAmount,...,roadNmBonbun,roadNmBubun,roadNmCd,roadNmSeq,roadNmSggCd,roadNmbCd,sggCd,slerGbn,umdCd,umdNm
0,,창신쌍용2,11110-91,0703,0000,1993,개인,,,"59,000",...,00198,00000,4100020,02,11110,0,11110,개인,17400,창신동
1,,창신쌍용2,11110-91,0703,0000,1993,개인,,,"64,000",...,00198,00000,4100020,02,11110,0,11110,개인,17400,창신동
2,,현대,11110-90,0082,0000,2000,개인,,,"86,990",...,00246,00020,3000008,06,11110,0,11110,개인,18700,무악동
3,,현대,11110-90,0082,0000,2000,개인,,,"95,850",...,00246,00009,3000008,06,11110,0,11110,개인,18700,무악동
4,,종로중흥S클래스,11110-2339,0202,0003,2013,개인,,,"11,900",...,00028,00000,4100372,01,11110,0,11110,개인,17500,숭인동
5,,현대,11110-90,0082,0000,2000,개인,,,"117,800",...,00246,00020,3000008,06,11110,0,11110,개인,18700,무악동
6,,창신쌍용2,11110-91,0703,0000,1993,개인,,,"59,200",...,00198,00000,4100020,02,11110,0,11110,개인,17400,창신동
7,,경희궁자이(3단지),11110-2446,0233,0000,2017,개인,,,"215,000",...,00035,00000,4100002,01,11110,11110,개인,17700,평동,None
8,,종로중흥S클래스,11110-2339,0202,0003,2013,개인,,,"12,000",...,00028,00000,4100372,01,11110,0,11110,개인,17500,숭인동
9,,인왕산아이파크,11110-2212,0060,0000,2008,개인,,,"143,500",...,00009,00000,4100482,01,11110,0,11110,개인,18700,무악동

# 디버깅 코드

In [98]:
### 아마트 실거래가 데이터 수집 코드
from lxml import html
import bs4
aptTradeDataUrl = "http://apis.data.go.kr/1613000/RTMSDataSvcAptTradeDev/getRTMSDataSvcAptTradeDev?serviceKey=AT33s775KYpJOkUBJu0dxkJuUeIfDIOJRzAH084EQS3JN%2BzFjErLHuk%2FGZa9L4gBTSGCzeA69tI9PwLp7B37IQ%3D%3D&LAWD_CD=11110&DEAL_YMD=202407&pageNo=1&numOfRows=10"
resp = requests.get(aptTradeDataUrl)
xmlObj = bs4.BeautifulSoup( resp.text, "lxml-xml")
# items을 찾아라!!!
# item이 각 행의 데이터셋이니깐 columnList에 저장하자!

rowList = []
columnList = []
columnNameList = []

itemTag = xmlObj.find(name="items")
itemList = itemTag.findAll(name="item")
# for j in range(0, len(itemList)):
j = 0
#itemList 한개를 가지고 rowList 만들어보자!
eachRow = itemList[j]
allColumns = eachRow.findAll()
# 전체컬럼 데이터를 columnList에 저장한다

In [100]:
i=0

In [101]:
# for i in range(0, len(allColumns)):
eachColumnValue = allColumns[i].text
columnList.append(eachColumnValue)

if j == 0:
    columnNameList.append( allColumns[i].name )