# Pandas 라이브러리를 활용한 데이터 수집 및 저장

# 3. 데이터베이스 데이터 수집 및 저장 (MongoDB)

### 라이브러리 선언하기

In [20]:
!pip install pymongo

Requirement already satisfied: pymongo in /usr/local/lib/python3.10/dist-packages (4.8.0)
Requirement already satisfied: dnspython<3.0.0,>=1.16.0 in /usr/local/lib/python3.10/dist-packages (from pymongo) (2.6.1)

In [21]:
# Pandas 패키지 불러오기
import pandas as pd
from pymongo.mongo_client import MongoClient
from pymongo.server_api import ServerApi

### 1. 파일 데이터 불러오기

In [22]:
# CSV 파일을 읽어 Data Frame 변수에 저장하기
# selloutLocalUrl = "../dataset/kopo_product_volume.csv"
selloutGitUrl = "https://raw.githubusercontent.com/hyokwan/python-lecture/master/dataset/kopo_product_volume.csv"
selloutData = pd.read_csv(selloutGitUrl)

selloutData.head()

  REGIONID PRODUCTGROUP  YEARWEEK  VOLUME
0      A01       ST0001    201415  810144
1      A01       ST0002    201415  128999
2      A01       ST0001    201418  671464
3      A01       ST0002    201418  134467
4      A01       ST0001    201413  470040

In [23]:
type(selloutData)

pandas.core.frame.DataFrame

### 2. MongoDB에 데이터프레임 저장

In [34]:
# MongoDB 연결 정보 설정
# user = "hkcode"
# password = "1234"
# host = '127.0.0.1'
# port = 27017
# database = 'hdb'

# MongoClient 로컬 접속
# uri = f"mongodb://{user}:{password}@{host}:{port}/{database}?authSource=admin"
# client = MongoClient(uri)

# uri = "클라우드 접속주소"
# Mongo클라우드 접속
# Create a new client and connect to the server
client = MongoClient(uri, server_api=ServerApi('1'))

try:
    # 연결 확인 (서버 정보 가져오기)
    server_info = client.server_info()
    print("Connected to MongoDB server:", server_info)
except ConnectionFailure as e:
    print("Could not connect to MongoDB server:", e)

Connected to MongoDB server: {'version': '7.0.12', 'gitVersion': 'b6513ce0781db6818e24619e8a461eae90bc94fc', 'modules': ['enterprise'], 'allocator': 'tcmalloc', 'javascriptEngine': 'mozjs', 'sysInfo': 'deprecated', 'versionArray': [7, 0, 12, 0], 'bits': 64, 'debug': False, 'maxBsonObjectSize': 16777216, 'storageEngines': ['devnull', 'inMemory', 'queryable_wt', 'wiredTiger'], 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1723537542, 5), 'signature': {'hash': b'\xedJs\xfc\x83\xcd\xaa\x19\xd0;\xcf\xfe\xa6\xd98\xb9X=\xb44', 'keyId': 7351290462197514241}}, 'operationTime': Timestamp(1723537542, 5)}

### 3. MongoDB 데이터프레임 저장

In [ ]:
database = "hkcodedb2"

In [25]:
collection_name = "kopo_product_collect"

# 데이터베이스와 컬렉션 객체 생성
db = client[database]
collection = db[collection_name]

In [26]:
# 데이터프레임을 MongoDB에 저장
records = selloutData.to_dict(orient='records')
records

[{'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201415,
  'VOLUME': 810144},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201415,
  'VOLUME': 128999},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201418,
  'VOLUME': 671464},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201418,
  'VOLUME': 134467},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201413,
  'VOLUME': 470040},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201413,
  'VOLUME': 140297},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201411,
  'VOLUME': 524787},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201411,
  'VOLUME': 145509},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201416,
  'VOLUME': 764927},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201416,
  'VOLUME': 140313},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201419,
  'VOLUME': 682757},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201419,
  'VOLUME': 128668},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201414,
  'VOLUME': 428195},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201414,
  'VOLUME': 137488},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201412,
  'VOLUME': 486509},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201417,
  'VOLUME': 697502},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201417,
  'VOLUME': 127163},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201407,
  'VOLUME': 620392},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201407,
  'VOLUME': 146476},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201410,
  'VOLUME': 511679},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201410,
  'VOLUME': 153152},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201402,
  'VOLUME': 438251},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201402,
  'VOLUME': 123875},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201405,
  'VOLUME': 482381},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201405,
  'VOLUME': 180516},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201408,
  'VOLUME': 571781},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201408,
  'VOLUME': 156772},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201403,
  'VOLUME': 420290},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201403,
  'VOLUME': 114744},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201406,
  'VOLUME': 570412},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201406,
  'VOLUME': 139277},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201409,
  'VOLUME': 569545},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201409,
  'VOLUME': 141823},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201401,
  'VOLUME': 513598},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201401,
  'VOLUME': 155729},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201404,
  'VOLUME': 458431},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201404,
  'VOLUME': 137162},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201435,
  'VOLUME': 149570},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201438,
  'VOLUME': 693449},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201438,
  'VOLUME': 132870},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201433,
  'VOLUME': 679332},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201433,
  'VOLUME': 150105},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201441,
  'VOLUME': 624735},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201441,
  'VOLUME': 127720},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201436,
  'VOLUME': 826981},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201436,
  'VOLUME': 210006},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201439,
  'VOLUME': 636169},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201439,
  'VOLUME': 129992},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201434,
  'VOLUME': 846123},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201434,
  'VOLUME': 168303},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201432,
  'VOLUME': 677509},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201432,
  'VOLUME': 134564},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201437,
  'VOLUME': 717281},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201437,
  'VOLUME': 195106},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201440,
  'VOLUME': 647135},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201440,
  'VOLUME': 139629},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201435,
  'VOLUME': 833345},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201425,
  'VOLUME': 618699},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201425,
  'VOLUME': 128766},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201428,
  'VOLUME': 587529},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201428,
  'VOLUME': 142598},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201423,
  'VOLUME': 610479},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201423,
  'VOLUME': 125300},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201426,
  'VOLUME': 586721},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201426,
  'VOLUME': 135212},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201431,
  'VOLUME': 671138},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201431,
  'VOLUME': 140732},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201421,
  'VOLUME': 620290},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201421,
  'VOLUME': 132909},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201429,
  'VOLUME': 620882},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201429,
  'VOLUME': 154985},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201424,
  'VOLUME': 589613},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201424,
  'VOLUME': 139590},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201427,
  'VOLUME': 599043},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201427,
  'VOLUME': 184550},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201422,
  'VOLUME': 603104},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201422,
  'VOLUME': 143231},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201430,
  'VOLUME': 643984},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201430,
  'VOLUME': 133998},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201452,
  'VOLUME': 1197170},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201452,
  'VOLUME': 422468},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201453,
  'VOLUME': 757241},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201453,
  'VOLUME': 232523},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201443,
  'VOLUME': 627906},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201443,
  'VOLUME': 124142},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201451,
  'VOLUME': 863189},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201451,
  'VOLUME': 356271},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201446,
  'VOLUME': 644949},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201446,
  'VOLUME': 184242},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201449,
  'VOLUME': 835398},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201449,
  'VOLUME': 669711},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201444,
  'VOLUME': 623132},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201444,
  'VOLUME': 133493},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201447,
  'VOLUME': 681873},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201447,
  'VOLUME': 378339},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201442,
  'VOLUME': 639179},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201442,
  'VOLUME': 136559},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201450,
  'VOLUME': 752613},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201450,
  'VOLUME': 294579},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201445,
  'VOLUME': 621592},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201445,
  'VOLUME': 155032},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201448,
  'VOLUME': 1103665},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201448,
  'VOLUME': 1400339},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201512,
  'VOLUME': 151750},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201520,
  'VOLUME': 645626},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201520,
  'VOLUME': 125863},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201515,
  'VOLUME': 810144},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201515,
  'VOLUME': 128999},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201518,
  'VOLUME': 671464},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201518,
  'VOLUME': 134467},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201513,
  'VOLUME': 470040},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201513,
  'VOLUME': 140297},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201511,
  'VOLUME': 524787},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201511,
  'VOLUME': 145509},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201516,
  'VOLUME': 764927},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201516,
  'VOLUME': 140313},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201519,
  'VOLUME': 682757},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201519,
  'VOLUME': 128668},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201514,
  'VOLUME': 428195},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201514,
  'VOLUME': 137488},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201512,
  'VOLUME': 486509},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201517,
  'VOLUME': 697502},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201517,
  'VOLUME': 127163},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201507,
  'VOLUME': 620392},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201507,
  'VOLUME': 146476},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201510,
  'VOLUME': 511679},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201510,
  'VOLUME': 153152},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201502,
  'VOLUME': 438251},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201502,
  'VOLUME': 123875},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201505,
  'VOLUME': 482381},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201505,
  'VOLUME': 180516},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201508,
  'VOLUME': 571781},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201508,
  'VOLUME': 156772},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201503,
  'VOLUME': 420290},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201503,
  'VOLUME': 114744},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201506,
  'VOLUME': 570412},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201506,
  'VOLUME': 139277},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201509,
  'VOLUME': 569545},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201509,
  'VOLUME': 141823},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201501,
  'VOLUME': 513598},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201501,
  'VOLUME': 155729},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201504,
  'VOLUME': 458431},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201504,
  'VOLUME': 137162},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201535,
  'VOLUME': 149570},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201538,
  'VOLUME': 693449},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201538,
  'VOLUME': 132870},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201533,
  'VOLUME': 679332},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201533,
  'VOLUME': 150105},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201541,
  'VOLUME': 624735},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201541,
  'VOLUME': 127720},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201536,
  'VOLUME': 826981},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201536,
  'VOLUME': 210006},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201539,
  'VOLUME': 636169},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201539,
  'VOLUME': 129992},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201534,
  'VOLUME': 846123},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201534,
  'VOLUME': 168303},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201532,
  'VOLUME': 677509},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201532,
  'VOLUME': 134564},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201537,
  'VOLUME': 717281},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201537,
  'VOLUME': 195106},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201540,
  'VOLUME': 647135},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201540,
  'VOLUME': 139629},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201535,
  'VOLUME': 833345},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201525,
  'VOLUME': 618699},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201525,
  'VOLUME': 128766},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201528,
  'VOLUME': 587529},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201528,
  'VOLUME': 142598},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201523,
  'VOLUME': 610479},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201523,
  'VOLUME': 125300},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201526,
  'VOLUME': 586721},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201526,
  'VOLUME': 135212},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201531,
  'VOLUME': 671138},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201531,
  'VOLUME': 140732},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201521,
  'VOLUME': 620290},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201521,
  'VOLUME': 132909},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201529,
  'VOLUME': 620882},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201529,
  'VOLUME': 154985},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201524,
  'VOLUME': 589613},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201524,
  'VOLUME': 139590},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201527,
  'VOLUME': 599043},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201527,
  'VOLUME': 184550},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201522,
  'VOLUME': 603104},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201522,
  'VOLUME': 143231},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201530,
  'VOLUME': 643984},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201530,
  'VOLUME': 133998},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201605,
  'VOLUME': 661049},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201605,
  'VOLUME': 231214},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201603,
  'VOLUME': 531372},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201603,
  'VOLUME': 152763},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201601,
  'VOLUME': 651243},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201601,
  'VOLUME': 162801},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201608,
  'VOLUME': 671116},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201608,
  'VOLUME': 130000},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201606,
  'VOLUME': 881536},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201606,
  'VOLUME': 172230},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201552,
  'VOLUME': 1197170},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201552,
  'VOLUME': 422468},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201604,
  'VOLUME': 585025},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201604,
  'VOLUME': 197057},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201602,
  'VOLUME': 573198},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201602,
  'VOLUME': 137186},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201553,
  'VOLUME': 757241},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201553,
  'VOLUME': 232523},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201607,
  'VOLUME': 790430},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201607,
  'VOLUME': 161324},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201543,
  'VOLUME': 627906},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201543,
  'VOLUME': 124142},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201551,
  'VOLUME': 863189},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201551,
  'VOLUME': 356271},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201546,
  'VOLUME': 644949},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201546,
  'VOLUME': 184242},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201549,
  'VOLUME': 835398},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201549,
  'VOLUME': 669711},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201544,
  'VOLUME': 623132},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201544,
  'VOLUME': 133493},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0001',
  'YEARWEEK': 201547,
  'VOLUME': 681873},
 {'REGIONID': 'A01',
  'PRODUCTGROUP': 'ST0002',
  'YEARWEEK': 201547,
  'VOLUME': 378339},
 {'REGIONID': 'A01',

In [27]:
collection.insert_many(records)
print("Data inserted successfully into MongoDB collection:", collection_name)

Data inserted successfully into MongoDB collection: kopo_product_collect

### 4. 데이터 조회

In [29]:
db = client[database]
collection = db[collection_name]

# 컬렉션에서 데이터 조회
inDf = pd.DataFrame( collection.find() )
inDf

                          _id REGIONID PRODUCTGROUP  YEARWEEK  VOLUME
0    66bb03a18b9d758c0c2bf53c      A01       ST0001    201415  810144
1    66bb03a18b9d758c0c2bf53d      A01       ST0002    201415  128999
2    66bb03a18b9d758c0c2bf53e      A01       ST0001    201418  671464
3    66bb03a18b9d758c0c2bf53f      A01       ST0002    201418  134467
4    66bb03a18b9d758c0c2bf540      A01       ST0001    201413  470040
..                        ...      ...          ...       ...     ...
525  66bb071f8b9d758c0c2bf74c      A01       ST0002    201614  148835
526  66bb071f8b9d758c0c2bf74d      A01       ST0001    201641  746061
527  66bb071f8b9d758c0c2bf74e      A01       ST0002    201412  151750
528  66bb071f8b9d758c0c2bf74f      A01       ST0001    201420  645626
529  66bb071f8b9d758c0c2bf750      A01       ST0002    201420  125863

[530 rows x 5 columns]

In [32]:
db = client[database]
collection = db[collection_name]

# 컬렉션에서 데이터 조회
cursor = collection.find()


# 조회된 데이터를 데이터프레임으로 변환
selloutDf = pd.DataFrame(list(cursor))
selloutDf.shape

(530, 5)